# Generated by Django 5.0.4 on 2024-05-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_book_alter_admin_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='校区名称')),
                ('address', models.CharField(max_length=128, verbose_name='地址')),
                ('detail', models.TextField(verbose_name='简介')),
            ],
        ),
    ]
