# Generated by Django 5.0.4 on 2024-05-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biographical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('education', models.SmallIntegerField(choices=[(1, '小学'), (2, '初中'), (3, '高中'), (4, '本科'), (5, '研究生'), (6, '博士'), (7, '其它')], verbose_name='教育水平')),
                ('attachment', models.CharField(max_length=255, verbose_name='简历附件')),
            ],
        ),
    ]
