# Generated by Django 5.0.4 on 2024-05-02 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_biographical'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64, verbose_name='昵称')),
                ('avatar', models.CharField(default='/media/userAvatar/default.jpg', max_length=64, verbose_name='照片')),
                ('birth', models.DateTimeField(verbose_name='出生日期')),
                ('isgraduate', models.BooleanField(default=False, verbose_name='是否毕业')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.campus', verbose_name='校区')),
            ],
        ),
    ]
