# Generated by Django 5.0.4 on 2024-05-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_studentinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('image', models.CharField(max_length=128, verbose_name='图片')),
                ('audio', models.CharField(max_length=128, verbose_name='音频')),
                ('video', models.CharField(max_length=128, verbose_name='视频')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
        ),
    ]
