# Generated by Django 5.0.4 on 2024-06-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_stu'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
            ],
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': '管理员', 'verbose_name_plural': '管理员'},
        ),
        migrations.AlterModelOptions(
            name='biographical',
            options={'verbose_name': '简历', 'verbose_name_plural': '简历'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '图书', 'verbose_name_plural': '图书'},
        ),
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name': '校区', 'verbose_name_plural': '校区'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': '媒体', 'verbose_name_plural': '媒体'},
        ),
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
    ]
